name: Build and Generate APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Qt
        uses: jurplel/setup-qt@v1

      - name: Build Project
        run: |
          qmake
          make

      - name: Generate APK
        run: |
          # Add commands to generate APK from your project here
        # Example: androiddeployqt or another build tool

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-apk
          path: path/to/apk-file
