name: QT Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up MSYS2
        uses: microsoft/setup-msys2@v1
        with:
          install: mingw-w64-x86_64-toolchain
          msystem: MINGW64
      - name: Install QT
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.11'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw73'
          dir: '${{github.workspace}}/qt/'
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{env.Qt5_Dir}}/lib/cmake/" -G "CodeBlocks - MinGW Makefiles" -B '${{github.workspace}}'/build
      - name: Build Project
        run: cmake --build '${{github.workspace}}'/build --target YourProjectName
