name: Build and Generate APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Qt
        run: |
          choco install qt5-default
          setx PATH "%PATH%;C:\Qt\5.15.2\bin"
          setx QMAKE "C:\Qt\5.15.2\bin\qmake.exe"
          qmake --version
        shell: cmd

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          ndk-version: 21.4.7075529
          cmake-version: 3.10.2

      - name: Build Project
        run: |
          qmake -spec android-clang "ANDROID_ABIS=arm64-v8a" "ANDROID_SDK_ROOT=$env:ANDROID_SDK_ROOT" "ANDROID_NDK_ROOT=$env:ANDROID_NDK_ROOT" "ANDROID_NDK_HOST=windows-x86_64"
          nmake
        shell: cmd

      - name: Generate APK
        run: |
          androiddeployqt --input android-libmyapp.so-deployment-settings.json --output $env:GITHUB_WORKSPACE/android-build --android-platform android-29 --jdk $env:JAVA_HOME --gradle --sign myapp.keystore myapp_alias --storepass myapp_password
        shell: cmd

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-apk
          path: path/to/apk-file
